---
title: "Traffic stops case study"
author: "Ellie "hacker(wo)man supreme" Heffernan"
date: "10/21/2020"
output: html_document
---

#Load in packages & the data. 
```{r}
library(rio)
library(tidyverse)
library(ggplot2)
library(sf)
library(readr)

stops <- rio::import(file = "https://raw.githubusercontent.com/r-journalism/learn-r-journalism/master/content/mapping/case_study/data/hamden_stops.csv",format = "csv")
```

#Getting rid of bad data!
```{r}
stops <-stops %>% filter(InterventionLocationLatitude!=0)
```

#Downloading census tract shapefiles in Hamden using TIGRIS
```{r}
#Load the tigris package & set up some options
library(tigris)
options(tigris_use_cache = TRUE)
options(tigris_class = "sf")

#Get the shapefile
new_haven <-tracts(state = "CT",county = "New Haven",cb = T)
```

#Mapping!
```{r}
#Start with the shapefile layer
ggplot(new_haven) + geom_sf()+ geom_point(data = stops,aes(x = InterventionLocationLongitude,y = InterventionLocationLatitude),color = "red") + theme_void() + theme(panel.grid.major = element_line(color ="transparent")) + labs(title = "Traffic stops in Hamden")

```

#Visualizing the distribution of stops with layers
```{r}
#Start with the shapefile layer
ggplot() + geom_sf(data = new_haven, color = "black",fill = NA,size = 0.5)+ stat_density2d(data = stops, show.legend = F,aes(x  = InterventionLocationLongitude,y = InterventionLocationLatitude, fill =..level..,alpha=..level..),geom = "polygon",size = 4, bins=10)+scale_fill_gradient(low="deepskyblue2",high = "firebrick1",name="Distribution")+coord_sf(xlim = c(-73.067649,-72.743739),ylim = c(41.28,41.48))+labs(x=NULL,y=NULL,title = "Traffic stops distribution around Hamden",subtitle = NULL,caption="Source:data.ct.gov")+theme_void()+theme(panel.grid.major = element_line(colour = "transparent"))
```

#Make a column for race 
```{r}
stops$race <-ifelse(stops$SubjectEthnicityCode =="H","H",stops$SubjectRaceCode)

stops <- stops %>% mutate(race = case_when(race=="A"~"Asian",race=="B"~"Black",race=="H"~"Hispanic",race =="W"~"White"))
```

#Visualize like you did before but add a facet for race
```{r}
ggplot() + geom_sf(data = new_haven, color = "black",fill = NA,size = 0.5)+ stat_density2d(data = stops, show.legend = F,aes(x  = InterventionLocationLongitude,y = InterventionLocationLatitude, fill =..level..,alpha=..level..),geom = "polygon",size = 4, bins=10)+facet_wrap(~race)+ scale_fill_gradient(low="deepskyblue2",high = "firebrick1",name="Distribution")+coord_sf(xlim = c(-73.067649,-72.743739),ylim = c(41.28,41.48))+labs(x=NULL,y=NULL,title = "Traffic stops distribution around Hamden",subtitle = NULL,caption="Source:data.ct.gov")+theme_void()+theme(panel.grid.major = element_line(colour = "transparent"))
```









